### ISSUE TITLE
All captured images rotated into landscape

### ISSUE THREAD

**Issue by vishwajit76** [fluttercandies/flutter_wechat_camera_picker#24]
1.0 When clicking on the "confirm" button it’s stuck there for some seconds (shoot video is properly working).
2.0 When clicked in portrait mode it’s automatically going landscape.
3.0 Front camera captured image has a mirror problem.
![WhatsApp Image 2020-12-29 at 6 16 23 PM](https://user-images.githubusercontent.com/25575802/103473868-22a2fb00-4dc3-11eb-8a2f-5dfb7d970b77.jpeg)

**Comment by AlexV525** [comment]
1 is related to your device performance, because there is a process of "saving the image data to file", while the video has been written during the shooting so you won't notice the lagging.
2 We don't have related problem about portrait and landscape while testing, please provide your usage code.
3 the `camera` which we're using might have the same problem. Could you try it's demo to see if it exist?

**Comment by vishwajit76** [comment]
> 1 is related to your device performance, because there is a process of "saving the image data to file", while the video has been written during the shooting so you won't notice the lagging.
> 2 We don't have related problem about portrait and landscape while testing, please provide your usage code.
> 3 the `camera` which we're using might have the same problem. Could you try it's demo to see if it exist?

Problem Facing On

Samsung Galaxy A8
Samsung Galaxy A31
One Plus Nord 
Samsung M30
One Plus 6
Redmi Note 9
Realme 5pro

In some devices work properly.

**Comment by AlexV525** [comment]
> Problem Facing On

Which problem?
